.\" man page create by R# package system.
.TH METABOLON 1 2000-1月 "as.render" "as.render"
.SH NAME
as.render \- 
.SH SYNOPSIS
\fIas.render(\fBnetwork\fR as <generic> metabolon_network, 
\fBassociation\fR as <generic> association_matrix_v6);\fR
.SH SEE ALSO
Metabolon
.SH FILES
.PP
MetaboLights.dll
.PP
