.TH COMBINE_SAMPLEINFO 1 2024-Oct "" "Combine the matrix with sampleinfo"
.SH NAME
combine_sampleinfo \- combine_sampleinfo(x, sampleinfo)
.SH SYNOPSIS
\fIcombine_sampleinfo(x, sampleinfo)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . 
.PP
.PP
\fBsampleinfo\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.combine_sampleinfo at combine_sampleinfo.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
