.TH EXTRACT_SPECTRA 1 2025-Mar "" "Workflow function for extract the reference spectrum"
.SH NAME
extract_spectra \- extract_spectra(maf, rawfiles,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIextract_spectra(maf, rawfiles,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBmaf\fB \fR\- . a character vector of the file path to the maf annotation result table tsv files.
.PP
.PP
\fBrawfiles\fB \fR\- . a character vector of the raw data files, should be in mzpack data format!
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.extract_spectra at spectrum.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
