.TH PATHMAPS 1 2025-Feb "" "rendering the pathway map"
.SH NAME
pathmaps \- pathmaps(
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>highlights</i> = <span style='color: blue !important;'>NULL</span>,
    <i>default.fill.color</i> = <span style='color: #D3D3D3;'><strong>'lightgray'</strong></span>)
.SH SYNOPSIS
\fIpathmaps(
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>highlights</i> = <span style='color: blue !important;'>NULL</span>,
    <i>default.fill.color</i> = <span style='color: #D3D3D3;'><strong>'lightgray'</strong></span>)\fR
.SH OPTIONS
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.PP
\fBhighlights\fB \fR\- NULL. 
.PP
.PP
\fBdefault.fill.color\fB \fR\- 'lightgray'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pathmaps at pathway.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
