.TH PATHWAY_METABOLITES 1 2025-Feb "" "pathway_metabolites"
.SH NAME
pathway_metabolites \- pathway_metabolites(cas.id)
.SH SYNOPSIS
\fIpathway_metabolites(cas.id)\fR
.SH OPTIONS
.PP
\fBcas.id\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pathway_metabolites at pathway.R:line 41
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
