.TH READJSON 1 2026-Jan "" "readJSON"
.SH NAME
readJSON \- readJSON(name, what)
.SH SYNOPSIS
\fIreadJSON(name, what)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . 
.PP
.PP
\fBwhat\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.readJSON at pathway.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
