.\" man page create by R# package system.
.TH MTBLSSTUDY 1 2000-1月 "read.study_source" "read.study_source"
.SH NAME
read.study_source \- read the metabolights study file
.SH SYNOPSIS
\fIread.study_source(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read the metabolights study file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- a file path to the metabolights study maf tsv table file.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
MTBLSStudy
.SH FILES
.PP
MetaboLights.dll
.PP
