.\" man page create by R# package system.
.TH REPOSITORY 1 2000-Jan "as.metaSet" "as.metaSet"
.SH NAME
as.metaSet \- Convert as dataset collection
.SH SYNOPSIS
\fIas.metaSet(\fBdatabase\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Convert as dataset collection
.PP
.SH OPTIONS
.PP
\fBdatabase\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
MetaboLights.dll
.PP
