.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "keywordFilters" "keywordFilters"
.SH NAME
keywordFilters \- filter the studies collection with a given set of the keywords
.SH SYNOPSIS
\fIkeywordFilters(\fBstudies\fR as any, 
\fBkeywords\fR as string, 
\fBignoreCase\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
filter the studies collection with a given set of the keywords
.PP
.SH OPTIONS
.PP
\fBstudies\fB \fR\- -. 
.PP
.PP
\fBkeywords\fB \fR\- -. 
.PP
.PP
\fBignoreCase\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
MetaboLights.dll
.PP
