.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "loadMetaEntries" "loadMetaEntries"
.SH NAME
loadMetaEntries \- load the complete metabolights database
.SH SYNOPSIS
\fIloadMetaEntries(\fBfile\fR as string, 
\fBtqdm\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
load the complete metabolights database
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- should be a file path to the complete metabolights 
 database file: \fBeb-eye_metabolights_complete.xml\fR. 
.PP
.PP
\fBtqdm\fB \fR\- 
 apply of the tqdm progress bar wrapper?
. 
.PP
.SH VALUE
.PP
a collection of the data @\fBT:MetaboLights.entry\fR objects
.PP
.SH DETAILS
.PP
the database file could be download from the url link: 
 http://ftp.ebi.ac.uk/pub/databases/metabolights/eb-eye/eb-eye_metabolights_complete.xml
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
MetaboLights.dll
.PP
