.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "metabolites" "metabolites"
.SH NAME
metabolites \- get metabolites data from the database repository
.SH SYNOPSIS
\fImetabolites(\fBdatabase\fR as any, 
\fBmzkit\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get metabolites data from the database repository
.PP
.SH OPTIONS
.PP
\fBdatabase\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH EXAMPLES
.PP
require(MetaboLights);
 
 const source_repo = "/path/to/eb-eye_metabolights_complete.xml";
 const data_repo = loadMetaEntries(source_repo) |> as.metaSet();
 const metabos_data = data_repo |> metabolites();
 
 write.csv(metabos_data, file = "/path/to/metabolites.csv");
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
MetaboLights.dll
.PP
