.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "parseChEBIEntity" "parseChEBIEntity"
.SH NAME
parseChEBIEntity \- Parse the chebi entity
.SH SYNOPSIS
\fIparseChEBIEntity(\fBxml\fR as string);\fR
.SH DESCRIPTION
.PP
Parse the chebi entity
.PP
.SH OPTIONS
.PP
\fBxml\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
MetaboLights.dll
.PP
